spring:
  application:
    name: sellia-api
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/sellia_db
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Jackson Configuration
  jackson:
    time-zone: UTC
    date-format: dd-MM-yyyy HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Application Configuration
app:
  server-url: http://localhost:8080
  base-url: http://localhost:4200  # Frontend URL for QR code generation
  jwt:
    secret: SevvwQ3vogESlsvgFTgBoXqfnbVeSsJiC917Mi7ZprAloOegCz5NNEuWwktK4qqoT0DDAPzsvtEBm0XLmUBNIQ==
    access-token-expiration: 3600000  # 1 hour in milliseconds
    refresh-token-expiration: 432000000  # 5 days in milliseconds
  
  upload-dir: ./uploads
  qr-codes-dir: ./uploads/qrcodes
  products-images-dir: ./uploads/products
  receipts-dir: ./uploads/receipts
  
  # Default Admin Configuration
#  admin:
#    email: admin@sellia.com
#    password: Admin123!
#    first-name: Admin
#    last-name: System

# Actuator Configuration (minimal)
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.follysitou.sellia_backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"